name: CI Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
# MAUI Android Build
  build-android:
    runs-on: windows-2022
    environment: Dev
    name: Android Build
    steps:
       #substitute production appsettings entries to appsettings json file
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'AppSettings.json'
        env:
          test: testWorks
    #     run: |
    #         echo "IsItMasked"
    #         echo "--------------"
    #         echo ${{secrets.SECRET1}}
    #         echo "--------------"
    #         echo ${{secrets.SECRET1}} | sed 's/./& /g'    
    #         echo "env stuff"
    # 


