name: CI Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:

# MAUI Windows Build
  build-windows:
    runs-on: windows-2022
    environment: Dev
    name: Windows Build
    steps:

      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Open Dir
        run: |
          dir
          cd ./Maui_Github_Actions_KeyVault_Test
          dir
          cat ./users.json
          echo "IsItMasked"
          echo "--------------"
          echo ${{secrets.SECRET1}}
          echo "--------------"
          echo ${{secrets.SECRET1}} | sed 's/./& /g'    
          echo "env stuff"

      - name:  substitute var 
        uses: microsoft/variable-substitution@v1 
        with:
          files: './Maui_Github_Actions_KeyVault_Test/users.json'
        env:
          name: ${{secrets.SECRET1}}

      - name: cat file
        run: |
             cat ./Maui_Github_Actions_KeyVault_Test/users.json
             cat ./Maui_Github_Actions_KeyVault_Test/users.json | sed 's/./& /g' 
